#!/bin/sh
#
# Wrapper script to look at the provided script and resolve
# any Maven dependencies before running the script with the
# relevant classpath set.
#
# For convenience, add this script somewhere in the path, so
# that scripts can start with:
#
# #!/usr/bin/env jjs-with-deps
#
# following which, they should add commented lines of the form:
#
# # dep:<groupId>:<artifactId>:<version>
# # dep:org.apache.commons:commons-lang3:3.3.2

# Uncomment the line below to enable debugging messages.
#DEBUG=1

jjsjs="$(dirname $(realpath $0))/jjs-with-deps.js"
jjs -scripting $jjsjs -- $@
